openapi: 3.0.0
info:
  version: '0.1'
  title: 'Recipes server API'
  license:
    name: MIT
servers:
  - url: 'https://rs-recipes-server.herokuapp.com'
paths:
  /recipes:
    get:
      summary: 'Returns array of recipe objects'
      tags:
        - recipe
      parameters:
        - name: page
          in: query
          description: 'Page number to return (0 is default)'
          required: false
          schema:
            type: integer
            format: int32
        - name: limit
          in: query
          description: 'Recipes per page (20 is default)'
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Array of recipe objects'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfRecipes'
  /recipes/{id}:
    get:
      summary: 'Returns recipe by its id'
      tags:
        - recipe
      parameters:
        - name: id
          in: path
          description: ID of the recipe
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: 'Recipe object'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Recipe'
        '404':
          description: 'Recipe for id not found'
  /recipes/distinct/{propertyPath}:
    get:
      summary: 'Returns distinct property values, specified in propertyPath'
      tags:
        - recipe
      parameters:
        - name: propertyPath
          in: path
          description: Identifier of property
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'An array of all distinct properties, specified in propertyPath'
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
        '400':
          description: 'propertyPath was not provided'
        '404':
          description: 'Provided recipe property path was not found'

components:
  schemas:
    Recipe:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
        vegetarian:
          type: boolean
        glutenFree:
          type: boolean
        dairyFree:
          type: boolean
        veryHealthy:
          type: boolean
        cheap:
          type: boolean
        veryPopular:
          type: boolean
        preparationMinutes:
          type: integer
        cookingMinutes:
          type: integer
        aggregateLikes:
          type: integer
        healthScore:
          type: integer
        pricePerServing:
          type: number
          format: float
        extendedIngredients:
          type: array
          items:
            type: object
            properties:
              id:
                type: number
              aisle:
                type: string
              image:
                type: string
              name:
                type: string
              nameClean:
                type: string
              original:
                type: string
              originalName:
                type: string
              amount:
                type: number
              unit:
                type: string
              measures:
                type: object
                properties:
                  us:
                    type: object
                    properties:
                      amount:
                        type: number
                      unitShort:
                        type: string
                      unitLong:
                        type: string
                  metric:
                    type: object
                    properties:
                      amount:
                        type: number
                      unitShort:
                        type: string
                      unitLong:
                        type: string
        title:
          type: string
        readyInMinutes:
          type: number
        servings:
          type: number
        sourceUrl:
          type: string
        image:
          type: string
        imageType:
          type: string
        nutrition:
          type: object
          properties:
            nutrients:
              type: array
              items:
                type: object
                properties:
                  name:
                    type: string
                  amount:
                    type: number
                  unit:
                    type: string
                  percentOfDailyNeeds:
                    type: number
        summary:
          type: string
        cuisines:
          type: array
          items:
            type: string
        dishTypes:
          type: array
          items:
            type: string
        diets:
          type: array
          items:
            type: string
        instructions:
          type: string
        analyzedInstructions:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              steps:
                type: array
                items:
                  type: object
                  properties:
                    number:
                      type: number
                    step:
                      type: string
                    ingredients:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: number
                          name:
                            type: string
                          localizedName:
                            type: string
                          image:
                            type: string
                    equipment:
                      type: array
                      items:
                        type: object
                        properties:
                          id:
                            type: number
                          name:
                            type: string
                          localizedName:
                            type: string
                          image:
                            type: string

    ArrayOfRecipes:
      type: array
      items:
        $ref: '#/components/schemas/Recipe'
    User:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
security:
  - BasicAuth: []
